{{- if .Values.defaultVaultConnection.mtls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mtls-cert-secret
type: Opaque
data:
  caCert: {{ .Files.Get .Values.defaultVaultConnection.mtls.caCertFilePath | b64enc | quote }}
  clientCert: {{ .Files.Get .Values.defaultVaultConnection.mtls.clientCertFilePath | b64enc | quote }}
  clientKey: {{ .Files.Get .Values.defaultVaultConnection.mtls.clientKeyFilePath | b64enc | quote }}
{{- end }}